movierecomm/movierecomm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^reviews/', include('reviews.urls', namespace="reviews")),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace="auth")),
]

movierecomm/reviews/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^$', views.review_list, name='review_list'),
    # ex: /review/5/
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    # ex: /wine/
    url(r'^movie$', views.movie_list, name='movie_list'),
    # ex: /wine/5/
    url(r'^movie/(?P<movie_id>[0-9]+)/$', views.movie_detail, name='movie_detail'),
    url(r'^movie/(?P<movie_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    # ex: /review/user - get reviews for the logged user
    url(r'^review/user/(?P<userid>\w+)/$', views.user_review_list, name='user_review_list'),
    # ex: /review/user - get reviews for the user passed in the url
    url(r'^review/user/$', views.user_review_list, name='user_review_list'),
    # ex: /recommendation - get wine recommendations for the logged user
    url(r'^recommendation/$', views.user_recommendation_list, name='user_recommendation_list'),
]

movierecomm/reviews/models.py
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User
import numpy as np
# Create your models here.

class Movie(models.Model):
    movieId = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=256)
    genres = models.CharField(max_length=256, null=True)

    def __str__(self):
        return "{title:\"%s\",genres:\"%s\", rating:%, id:%d}"  %(self.user.username, self.movie.title, self.ratin, self.movieId)

    def average_rating(self):
        all_ratings = map(lambda x:x.rating, self.review_set.all())
        return np.mean(all_ratings)


class Review(models.Model):
    RATING_CHOICES = (
            (0, '0'),
            (1, '1'),
            (2, '2'),
            (3, '3'),
            (4, '4'),
            (5, '5'),
    )
    user = models.ForeignKey(User)
    movie = models.ForeignKey(Movie)
    rating = models.IntegerField(choices=RATING_CHOICES)
    comment = models.CharField(max_length=1024, null=True)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return "{user:\"%s\",movie:\"%s\", rating:%d, id: %d}"  %(self.user.username, self.movie.title, self.rating, self.id)

    class Meta:
        unique_together = (('user', 'movie'),)

class RecommendedMovieList(models.Model):
    user = models.ForeignKey(User)
    movie = models.ForeignKey(Movie)
    priority = models.IntegerField()

    ALGO_CHOICES = (
            ('KMEAN', 'KMEAN'),
            ('KNN', 'KNN'),
    )

    algo = models.CharField(max_length=128, default='NAIVE')

    def __str__(self):
        return "{user:\"%s\",movie:\"%s\", priority:%d, algo:%s}"  %(self.user.username, self.movie.title, self.priority, self.algo)

    class Meta:
        unique_together = (('user', 'movie', 'algo'),)


movierecomm/reviews/forms.py
from django.forms import ModelForm, Textarea
from reviews.models import Review


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),
        }

movierecomm/reviews/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from .models import Review, Movie, RecommendedMovieList
from .forms import ReviewForm
from .recommendation_algo import update_recommendation_by_review
import datetime

from multiprocessing import Process

from django.contrib.auth.decorators import login_required
# Create your views here.

def review_list(request):
    latest_review_list = Review.objects.order_by('-pub_date')[:6] #.values('user__username', 'movie__title', 'rating','comment')
    context = {'latest_review_list':latest_review_list}
    return render(request, 'reviews/review_list.html', context)


def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'reviews/review_detail.html', {'review': review})


def movie_list(request):
    movie_list = Movie.objects.order_by('-title')
    context = {'movie_list':movie_list}
    return render(request, 'reviews/movie_list.html', context)


def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    form = ReviewForm()
    return render(request, 'reviews/movie_detail.html', {'movie':movie, 'form':form})

@login_required
def add_review(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        rating = form.cleaned_data['rating']
        comment = form.cleaned_data['comment']
        try:
            review = Review.objects.get(user_id=request.user.id, movie_id=movie_id)
            review.rating = rating
            review.save(update_fields=['rating', 'comment'])
#            update_recommendation_by_review((request.user.id, movie_id), 'update')
            # start a process to update recommendations
            p = Process(target=update_recommendation_by_review, args=((request.user.id, movie_id), 'update'))
            p.start()
        except Review.DoesNotExist :
            review = Review()
            review.movie = movie
            review.user = request.user
            review.rating = rating
            review.comment = comment
            review.pub_date = datetime.datetime.now()
            review.save()
#            update_recommendation_by_review((request.user.id, movie_id), 'add')
            p = Process(target=update_recommendation_by_review, args=((request.user.id, movie_id), 'add'))
            p.start()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('reviews:movie_detail', args=(movie.movieId,)))
    
    return render(request, 'reviews/movie_detail.html', {'movie': movie, 'form': form})
    

def user_review_list(request, userid=None):
    if not userid:
        userid = request.user.id
    latest_review_list = Review.objects.filter(user__id=userid).order_by('-pub_date')
    context = {'latest_review_list':latest_review_list, 'username':request.user.username}
    return render(request, 'reviews/user_review_list.html', context)


@login_required
def user_recommendation_list(request):
    recomm = RecommendedMovieList.objects.filter(user_id=request.user.id).order_by('priority').prefetch_related('movie')[:10]
    movie_list = [] # [r.movie for r in recomm]
    for m in recomm:
        m.movie.priority = m.priority
        m.movie.algoName = m.algo
        movie_list.append(m.movie)

    return render(
        request, 
        'reviews/recommendation_list.html', 
        {'username': request.user.username,'movie_list': movie_list}
    )
    




movierecomm/reviews/templates/reviews/movie_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
<h2>{{ movie.title }}</h2>
<h5>{{ movie.review_set.count }} reviews ({{ movie.average_rating | floatformat }} average rating)</h5>
{% endblock %}

{% block content %}
<h3>Recent reviews</h3>

{% if movie.review_set.all %}
<div class="row">
    {% for review in movie.review_set.all %}
    <div class="col-xs-6 col-lg-4">
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by <a href="{% url 'reviews:user_review_list' review.user.id %}" >{{ review.user.username }}</a></h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this wine yet</p>
{% endif %}

<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'reviews:add_review' movie.movieId %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Add
    </button>
    {% endbuttons %}
</form>
{% endblock %}

movierecomm/reviews/templates/reviews/movie_list.html
{% extends 'base.html' %}

{% block title %}
<h2>Movie list</h2>
{% endblock %}

{% block content %}
{% if movie_list %}
<div class="row">
    {% for movie in movie_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'reviews:movie_detail' movie.movieId %}">
        {{ movie.title }}
        </a></h4>
        <h5>{{ movie.review_set.count }} reviews</h5>
        <h5>{{ movie.average_rating | floatformat }} average rating</h5>
        {% if movie.priority %}
            <h5> recommendation priority: {{ movie.priority }} </h5>
            <h5> recommendation algo: {{ movie.algoName }} </h5>
        {% endif %}
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No movies are available.</p>
{% endif %}
{% endblock %}

movierecomm/reviews/templates/reviews/recommendation_list.html
{% extends 'reviews/movie_list.html' %}

{% block title %}
<h2>Movie suggestions for {{ username }}</h2>
{% endblock %}

movierecomm/reviews/templates/reviews/review_detail.html
{% extends 'base.html' %}

{% block title %}
<h2><a href="{% url 'reviews:movie_detail' review.movie.movieId %}">{{ review.movie.title }}</a></h2>
{% endblock %}

{% block content %}
<h4>Rated {{ review.rating }} of 5 by <a href="{% url 'reviews:user_review_list' review.user.id %}" >{{ review.user.username }}</a></h4>
<p>{{ review.pub_date }}</p>
<p>{{ review.comment }}</p>
{% endblock %}

movierecomm/reviews/templates/reviews/review_list.html
{% extends 'base.html' %}

{% block title %}
<h2>Latest reviews</h2>
{% endblock %}

{% block content %}
{% if latest_review_list %}
<div class="row">
    {% for review in latest_review_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'reviews:review_detail' review.id %}">
        {{ review.movie.title }}
        </a></h4>
        <h6>Rated {{ review.rating }} of 5 by 
            <a href="{% url 'reviews:user_review_list' review.user.id %}" >{{ review.user.username }}</a>
        </h6>
        <p>{{ review.comment }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}
{% endblock %}

movierecomm/reviews/templates/reviews/user_review_list.html
{% extends 'reviews/review_list.html' %}

{% block title %}
<h2>Reviews by {{ username }}</h2>
{% endblock %}

movierecomm/templates/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'reviews:review_list' %}">Movie Recommendations</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'reviews:review_list' %}">Review List</a></li>
                <li><a href="{% url 'reviews:movie_list' %}">Movie List</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'reviews:user_recommendation_list' %}">Movie suggestions</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'reviews:user_review_list' user.id %}">Hello {{ user.username }}</a></li>
                <li><a href="{% url 'auth:logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'auth:login' %}">Login</a></li>
                <li><a href="/accounts/register">Register</a></li>
            {% endif %}
            </ul>
        </div>
    </nav>
    

    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}